### ISSUE TITLE
Add any information for repeatable words

### ISSUE THREAD

**Issue by SlayksWood** [queleok/words-hunter#14]
Something like that:
![image](https://user-images.githubusercontent.com/45708377/98684781-a1595a00-2377-11eb-9297-fac0bb53050f.png)

**Comment by queleok** [comment]
That's one of the points in #2 , but maybe it makes sense to split that case into several independent ones using original case as an umbrella for several tasks

**Comment by queleok** [comment]
I don't particularly like the idea of allowing repetitive words in the list, so instead of that upon an attempt to enter existing word I'll move such a word at the top of the list and add shaking animation for it
