### ISSUE TITLE
Highlight letter that you type.

### ISSUE THREAD

**Issue by SlayksWood** [queleok/words-hunter#15]
We suggest adding highlighting letters that we are typing. It could be first letter in a massive. Something like this:
![image](https://user-images.githubusercontent.com/45708377/99822360-2b69a580-2b64-11eb-849f-8c1026ef7e9e.png)

**Comment by queleok** [comment]
Unfortunately the task is not as trivial as I hoped. The issue stems from the facts that
- the plain input element provides too much freedom to the user;
- different browsers and different operating systems have different ways of handling different ways in which the user can modify the contents of the input.

The aforementioned different ways of input modification include:
- vanilla (without previous selection) input of new characters (the simplest & well-handled case);
- modification of already inserted text with navigation->selection->insertion/deletion (deletion with backspace or delete is well-handled, while cutting can be simply disabled, but the possibility of insertion of a new character after selection );
- pasting from clipboard;
- undoing/redoing.

Maybe it's time to move away from vanilla JS & look for some library or framework that would conveniently hide these complications from me :)

**Comment by queleok** [comment]
Actually turns out `beforeinput` and `input` events allow handling most of the use-cases, so maybe it's not that hard after all
