### ISSUE TITLE
Too many repetitive letters

### ISSUE THREAD

**Issue by SlayksWood** [queleok/words-hunter#7]
I have 5 'A's here:
![image](https://user-images.githubusercontent.com/45708377/98440430-b0d36b80-2109-11eb-8c72-e0bf96357bae.png)
Our suggestion:
use no more than 3 repeat vowels and 2 repeat consonants in a set.

**Comment by queleok** [comment]
There should probably also be some limits on the proportion of vowels and consonants, like minimum 2 vowels and 4 consonants. I'm going to use [Peter Norvig's dict of unigrams|http://norvig.com/mayzner.html] to come up with a more reasonable distribution & limits.

**Comment by queleok** [comment]
Alright, I guess the biggest issue with the existing solution is that I put no thought in normalization of the resulting distribution

**Comment by queleok** [comment]
I have a feeling that I'm trying to attack this from the wrong angle, but I guess this is what you get for having a pet project :) Nonetheless, I've put jupyter notebook with some thoughts on improvements to the current algorithm in the `docs` folder. The next steps are:
- fit function for the first vowels generation
- check in the jupyter how letters redistribution works
- implement it in JS & deploy

Any hits to better angles of attack would be much appreciated.

**Comment by queleok** [comment]
In the last commit I've also implemented the algorithm in python and played with it a bit. Didn't really like the results with the frequency map built from the wiki-100k dictionary (there were too many vowels generated, I suspect some french words are messing up the statistics), so I think going with the Cornell's frequency map as the base distribution should be fine. The next step are as follows:
- implement solver for the game to be able to measure quality of the generated field and hence compare different approaches;
- implement field generator in JS.
