### ISSUE TITLE
插件导致的页面未响应

### ISSUE THREAD

**Issue by majiayu000** [queleok/words-hunter#73]
**Describe the bug**
这个插件会导致页面未响应，原因不太明白。机器配置很高，以前从来没出现这种情况

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by queleok** [comment]
Would you mind elaborating on what you mean exactly in English? My mandarin skills are essentially nonexistent, and translations I get from the automatic translators are rather cryptic.

**Comment by majiayu000** [comment]
Sorry for the bother, it is only my fault.
